{
 "title": "XDP benchmark",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Send", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "curiosity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_packets_total{instance=\"curiosity\", device=\"bond0\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit (packet)"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"curiosity\",device=\"bond0\"}[$__rate_interval])*8 > 0",
     "legendFormat": "{{device}} - Transmit (Gbps)"
    }
   ]
  },
  { "title": "Load balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "apollo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{instance=\"apollo\", device=\"enp23s0f0np0\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{instance=\"apollo\", device=\"enp23s0f0np0\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "apollo (Gbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"apollo\", device=\"enp23s0f0np0\"}[$__rate_interval])*8 > 0",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"apollo\", device=\"enp23s0f0np0\"}[$__rate_interval])*8 > 0",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Softnet Out of Quota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_softnet_times_squeezed_total{instance=\"apollo\"}[$__rate_interval]) > 0",
     "legendFormat": "CPU {{cpu}} - Squeezed"
    }
   ]
  },
  {
   "title": "Context Switches / Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_context_switches_total{instance=\"apollo\"}[$__rate_interval])",
     "legendFormat": "Context switches"
    },
    {
     "expr": "rate(node_intr_total{instance=\"apollo\"}[$__rate_interval])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "buran",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{instance=\"buran\", device=\"enp23s0f0\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive (packet)"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"buran\",device=\"enp23s0f0\"}[$__rate_interval])*8 > 0",
     "legendFormat": "{{device}} - Receive (Gbps)"
    }
   ]
  },
  {
   "title": "clementine",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{instance=\"clementine\", device=\"enp23s0f0\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive (packet)"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"clementine\",device=\"enp23s0f0\"}[$__rate_interval])*8 > 0",
     "legendFormat": "{{device}} - Receive (Gbps)"
    }
   ]
  },
  {
   "title": "davinci",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{instance=\"davinci\", device=\"enp23s0f0\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive (packet)"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"davinci\",device=\"enp23s0f0\"}[$__rate_interval])*8 > 0",
     "legendFormat": "{{device}} - Receive (Gbps)"
    }
   ]
  }
 ]
}